// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: internel/proto/upload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileUrl   string `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *PictureRequest) Reset() {
	*x = PictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internel_proto_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureRequest) ProtoMessage() {}

func (x *PictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internel_proto_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureRequest.ProtoReflect.Descriptor instead.
func (*PictureRequest) Descriptor() ([]byte, []int) {
	return file_internel_proto_upload_proto_rawDescGZIP(), []int{0}
}

func (x *PictureRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *PictureRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PictureReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int64              `protobuf:"varint,1,opt,name=Retcode,proto3" json:"Retcode,omitempty"`
	Data    *PictureReply_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PictureReply) Reset() {
	*x = PictureReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internel_proto_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureReply) ProtoMessage() {}

func (x *PictureReply) ProtoReflect() protoreflect.Message {
	mi := &file_internel_proto_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureReply.ProtoReflect.Descriptor instead.
func (*PictureReply) Descriptor() ([]byte, []int) {
	return file_internel_proto_upload_proto_rawDescGZIP(), []int{1}
}

func (x *PictureReply) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *PictureReply) GetData() *PictureReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type PictureReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileUrl string `protobuf:"bytes,1,opt,name=FileUrl,proto3" json:"FileUrl,omitempty"`
}

func (x *PictureReply_Data) Reset() {
	*x = PictureReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internel_proto_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureReply_Data) ProtoMessage() {}

func (x *PictureReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_internel_proto_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureReply_Data.ProtoReflect.Descriptor instead.
func (*PictureReply_Data) Descriptor() ([]byte, []int) {
	return file_internel_proto_upload_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PictureReply_Data) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

var File_internel_proto_upload_proto protoreflect.FileDescriptor

var file_internel_proto_upload_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a,
	0x0e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x0c, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x32, 0x35, 0x0a,
	0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internel_proto_upload_proto_rawDescOnce sync.Once
	file_internel_proto_upload_proto_rawDescData = file_internel_proto_upload_proto_rawDesc
)

func file_internel_proto_upload_proto_rawDescGZIP() []byte {
	file_internel_proto_upload_proto_rawDescOnce.Do(func() {
		file_internel_proto_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_internel_proto_upload_proto_rawDescData)
	})
	return file_internel_proto_upload_proto_rawDescData
}

var file_internel_proto_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internel_proto_upload_proto_goTypes = []interface{}{
	(*PictureRequest)(nil),    // 0: PictureRequest
	(*PictureReply)(nil),      // 1: PictureReply
	(*PictureReply_Data)(nil), // 2: PictureReply.Data
}
var file_internel_proto_upload_proto_depIdxs = []int32{
	2, // 0: PictureReply.data:type_name -> PictureReply.Data
	0, // 1: Upload.Picture:input_type -> PictureRequest
	1, // 2: Upload.Picture:output_type -> PictureReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internel_proto_upload_proto_init() }
func file_internel_proto_upload_proto_init() {
	if File_internel_proto_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internel_proto_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internel_proto_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internel_proto_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internel_proto_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internel_proto_upload_proto_goTypes,
		DependencyIndexes: file_internel_proto_upload_proto_depIdxs,
		MessageInfos:      file_internel_proto_upload_proto_msgTypes,
	}.Build()
	File_internel_proto_upload_proto = out.File
	file_internel_proto_upload_proto_rawDesc = nil
	file_internel_proto_upload_proto_goTypes = nil
	file_internel_proto_upload_proto_depIdxs = nil
}
